[rooms.track_a]
name = "Track A"
# Add dates as needed when livestream URLs are known
# "2025-07-14" = "https://www.youtube.com/watch?v=..."

[rooms.track_b]
name = "Track B"
# Add dates as needed when livestream URLs are known
# "2025-07-14" = "https://www.youtube.com/watch?v=..."
